### PR TITLE
[UPDATE] snake game - Add red dot / Add trash code / Add 'Game End' and error modify

### PR DESCRIPTION
**Pull request by Ahnsanghyun-hi**
Add red dot in snake game.
But still not working len(snake).
I will fix it soon.

### CODE REVIEW

**Comment by wyuinche** [comment]
Does it work now?

**Comment by Ahnsanghyun-hi** [comment]
> Does it work now?

Yes, it works now

**Comment by Ahnsanghyun-hi** [comment]
Add trash code.
If snake eat trash, snake's length will decline.

**Comment by Ahnsanghyun-hi** [comment]
Add 'Game End' and error modify
if snake game end, Idle print 'Game End'.
And error modify. ( https://github.com/19-2-SKKU-OSS/2019-2-OSS-L8/issues/30 )

**Pull request merged**
